SL:87 #179 add password attribute to meeting
blindsidenetworks/scalelite pull request #466
Opened 2021-03-01 20:05 UTC by amalrails

#179

2021-03-01 22:15 UTC, kepstin requested changes
Using a static moderator password is not the way to handle this - if the moderator password is not passed on the request, a *random per-meeting* moderator password must be generated.

The moderator password should be saved per-meeting in the meeting hash in redis.

I recommend having scalelite save the moderator password used in the received create call, if there was none passed then generate a new random one, and then pass that password on to the backend BBB server.

The moderator password should be saved in redis in the meeting model.

2021-03-01 22:27 UTC, kepstin requested changes

2021-03-01 22:27 UTC, kepstin commented on app/models/meeting.rb
> +  define_attribute_methods :id, :server_id, :password
Please call the attribute `moderator_pw` so we don't get it confused with the attendee password.

2021-03-01 22:27 UTC, kepstin commented on app/controllers/bigbluebutton_api_controller.rb
> +    moderator_pwd = params[:moderatorPW] || Rails.configuration.x.moderator_pwd
Need to generate a new random password rather than using a static password.

2021-03-04 15:24 UTC, kepstin commented on app/controllers/bigbluebutton_api_controller.rb
> +    moderator_pwd = params[:moderatorPW] || SecureRandom.hex(6)
We should probably try to match BBB itself as closely as possible in the random password generation: the relevant code is here: https://github.com/bigbluebutton/bigbluebutton/blob/363c80133895ca68c7825b463f8ca22df2d7f918/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L647 (It generates a random alphanumeric 8-character string for the password using this function: http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html#randomAlphanumeric-int- )

2021-03-04 15:27 UTC, kepstin commented on app/controllers/bigbluebutton_api_controller.rb
> +    moderator_pwd = params[:moderatorPW] || SecureRandom.hex(6)
It looks like the `SecureRandom` class has this function builtin, you could so `SecureRandom.alphanumeric(8)`

2021-03-05 15:43 UTC, kepstin requested changes

2021-03-05 15:43 UTC, kepstin commented on app/controllers/bigbluebutton_api_controller.rb
> +    moderator_pwd = params[:moderatorPW] || SecureRandom.alphanumeric(8)
We need to handle the case of a blank value (empty string) here. Rails provides a helper for this:
```suggestion
    moderator_pwd = params[:moderatorPW].presence || SecureRandom.alphanumeric(8)
```

2021-03-18 00:49 UTC, jfederico approved these changes

2021-03-18 18:37 UTC, kepstin approved these changes

2021-03-18 19:30 UTC, merged